### ISSUE TITLE
hardcoded probe on M851 and _PROBE_OFFSET_REPORT

### ISSUE THREAD

**Issue by rediculum** [freakydude/klipper-serial-btt#13]
Hello

You have hardcoded "bltouch" as the probe in the M851 and _PROBE_OFFSET_REPORT gcode macro. 
```
[gcode_macro _PROBE_OFFSET_REPORT]
gcode:
  {% set OFFSET_X = printer.configfile.settings.bltouch.x_offset | default(0) - printer.gcode_move.homing_origin.x %}
  {% set OFFSET_Y = printer.configfile.settings.bltouch.y_offset | default(0) - printer.gcode_move.homing_origin.y %}
  {% set OFFSET_Z = printer.configfile.settings.bltouch.z_offset | default(0) - printer.gcode_move.homing_origin.z %}

  _SEND_TO_BTT COMMAND="M851 X{OFFSET_X} Y{OFFSET_Y} Z{OFFSET_Z}"
```
```
[gcode_macro M851]
description: XYZ Probe Offset
  Set the XYZ distance from the nozzle to the probe trigger-point.
gcode:
  #{% set X = params.X | default(0)| float %}
  #{% set Y = params.Y | default(0)| float %}
  #{% set Z = params.Z | default(0)| float %}

  {% set OFFSET_X = printer.configfile.settings.bltouch.x_offset | default(0) - printer.gcode_move.homing_origin.x %}
  {% set OFFSET_Y = printer.configfile.settings.bltouch.y_offset | default(0) - printer.gcode_move.homing_origin.y %}
  {% set OFFSET_Z = printer.configfile.settings.bltouch.z_offset | default(0) - printer.gcode_move.homing_origin.z %}

  {% if not (params.X is defined or params.Y is defined or params.Z is defined) %}
    _SEND_TO_BTT COMMAND="M851 X{OFFSET_X} Y{OFFSET_Y} Z{OFFSET_Z}"
  {% endif %}
```

For people like me who replaced it by an inductive sensor like SN04 and used the [probe] configuration instead of [bltouch], Klipper throws the following error on startup:
```
Error evaluating 'gcode_macro _PROBE_OFFSET_REPORT:gcode': jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'bltouch'
```

**Comment by freakydude** [comment]
Thanks informing me. 

in fact I use the BIQU Microprobe in meanwhile for myself and run into the same problem. This problem could solved easily. 
But the second issue is than, that strow/deploy is not standardized for the "probe". 

I don't have a good idea to solve that in general. 

If you like you could create a merge request how you fixed this? Think you just replaced the 'BLTouch' by 'probe' , right? Or did a if/else section like me locally. 

How is your probe activated / deactivated?

Best regards

**Comment by freakydude** [comment]
Ok, thank you

Seems like we have a third variant.

The BIQU (BigTreeTech) micro probe needs a probe enable/disable command in addition. It has a sensor and a control pin. (like the bltouch). But it is not compatible within klipper. So you have to use the `[probe]` section + `[output_pin]` section. 

https://github.com/bigtreetech/MicroProbe/blob/master/MicroProbe_User_Manual_20230616.pdf

Now the TouchScreen firmware has functions like stow/deploy the probe (Marlin `M401`/`M402`).

For BLTouch you have to call `BLTOUCH_DEBUG COMMAND=pin_up` or `BLTOUCH_DEBUG COMMAND=pin_down`
For BIQU Microprobe you have to enable, disable this control pin 

For your probe it seems like this is not possible at all?

**Comment by rediculum** [comment]
Seems that mechanical sensors have to be defined as ```bltouch``` and your BIQU even more complex and inductive sensors have to be defined as ```probe```. Since inductive probes only need 3 pins (5V,GND,Sensor), it cannot defined within ```bltouch``` because this section requires 2 data pins to be defined (sensor_pin & control_pin)
I corrected my config above
